breeze-agent kubernetes deployment v1.2

diff --git a/kubernetes/tunhub/breeze-agent-deployment-eks.yaml b/kubernetes/tunhub/breeze-agent-deployment-eks.yaml
--- a/kubernetes/tunhub/breeze-agent-deployment-eks.yaml
+++ b/kubernetes/tunhub/breeze-agent-deployment-eks.yaml
@@ -1,3 +1,50 @@
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: breeze-entrypoint
+data:
+  entrypoint.sh: |
+    #!/usr/bin/env bash
+
+    ERRORS=0
+
+    echo "Checking prerequisites..."
+
+    # check if node-tags file on breeze-data volume is mounted for EKS
+    if ! $(env | grep -qF 'cluster.arn' /opt/breeze-agent/etc/tags); then
+        echo "Running EKS specific checks..."
+        if ! [ -f /breeze-data/node-tags.json ]; then
+            echo "ERROR: /breeze-data/node-tags.json is missing; check volume mounts and init-container."
+            let ERRORS++
+        fi
+    else
+        echo "skipping EKS specific check"
+    fi
+
+    # check if dev-tun device is present
+    if ! [ -c /dev/net/tun ]; then
+        echo "ERROR: /dev/net/tun device is missing; check volume mounts."
+        let ERRORS++
+    fi
+
+    # check if required env vars are present
+    if ! $(env | grep -q 'BREEZE_RUNTIME=kubernetes' && env | grep -q 'BREEZE_K8S_TUNHUB_CLIENT=enabled'); then
+        echo "ERROR: check the required environment variables."
+        let ERRORS++
+    fi
+
+    # check tiny init process
+    if ! $(ps ax | grep -q '[t]ini'); then
+        echo "WARNING: 'tini' process is missing."
+    fi
+
+    echo $ERRORS
+    [[ ERRORS -eq 0 ]] || exit 1
+
+    echo "Starting Breeze daemon..."
+    /opt/breeze-agent/breeze-daemon
+
+---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -5,7 +52,7 @@ metadata:
   namespace: default
   labels:
     app.kubernetes.io/name: breeze-agent
-    app.kubernetes.io/version: v1.1
+    app.kubernetes.io/version: v1.2
 spec:
   replicas: 1
   selector:
@@ -15,7 +62,7 @@ spec:
     metadata:
       labels:
         app.kubernetes.io/name: breeze-agent
-        app.kubernetes.io/version: v1.1
+        app.kubernetes.io/version: v1.2
     spec:
       volumes:
       - name: breeze-data
@@ -24,6 +71,10 @@ spec:
         hostPath:
           path: /dev/net/tun
           type: CharDevice
+      - name: entrypoint
+        configMap:
+          name: breeze-entrypoint
+          defaultMode: 0755
       initContainers:
       - name: breeze-agent-init
         image: CONTAINER_REGISTRY_HOSTNAME/breeze-agent-init:latest
@@ -35,6 +86,7 @@ spec:
       - name: breeze-agent
         image: CONTAINER_REGISTRY_HOSTNAME/breeze-agent:latest
         imagePullPolicy: Always
+        args: ["/scripts/entrypoint.sh"]
         resources:
           requests:
             memory: "64Mi"
@@ -47,6 +99,8 @@ spec:
           mountPath: /breeze-data
         - name: dev-tun
           mountPath: /dev/net/tun
+        - name: entrypoint
+          mountPath: /scripts
         env:
           - name: BREEZE_RUNTIME
             value: kubernetes
@@ -57,9 +111,15 @@ spec:
           - name: BREEZE_K8S_TUNHUB_CLIENT
             value: enabled
         securityContext:
+          runAsNonRoot: true
+          runAsUser: 10000
+          runAsGroup: 10000
           privileged: false
           capabilities:
-            add: ["NET_ADMIN"]
+            add: [
+              "NET_ADMIN",
+              "NET_RAW"
+            ]
         readinessProbe:
           exec:
             command:
@@ -69,5 +129,3 @@ spec:
           initialDelaySeconds: 900
           periodSeconds: 60
           failureThreshold: 60
-      # imagePullSecrets:
-      # - name: IMAGE_PULL_SECRETS_NAME
diff --git a/kubernetes/tunhub/helm-chart/templates/configmap.yaml b/kubernetes/tunhub/helm-chart/templates/configmap.yaml
--- a/kubernetes/tunhub/helm-chart/templates/configmap.yaml
+++ b/kubernetes/tunhub/helm-chart/templates/configmap.yaml
@@ -1,3 +1,51 @@
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: breeze-entrypoint
+data:
+  entrypoint.sh: |
+    #!/usr/bin/env bash
+
+    ERRORS=0
+
+    echo "Checking prerequisites..."
+{{- if eq .Values.platform "eks" }}
+    # check if node-tags file on breeze-data volume is mounted for EKS
+    if ! $(env | grep -qF 'cluster.arn' /opt/breeze-agent/etc/tags); then
+        echo "Running EKS specific checks..."
+        if ! [ -f /breeze-data/node-tags.json ]; then
+            echo "ERROR: /breeze-data/node-tags.json is missing; check volume mounts and init-container."
+            let ERRORS++
+        fi
+    else
+        echo "skipping EKS specific check"
+    fi
+{{- end }}
+
+    # check if dev-tun device is present
+    if ! [ -c /dev/net/tun ]; then
+        echo "ERROR: /dev/net/tun device is missing; check volume mounts."
+        let ERRORS++
+    fi
+
+    # check if required env vars are present
+    if ! $(env | grep -q 'BREEZE_RUNTIME=kubernetes' && env | grep -q 'BREEZE_K8S_TUNHUB_CLIENT=enabled'); then
+        echo "ERROR: check the required environment variables."
+        let ERRORS++
+    fi
+
+    # check tiny init process
+    if ! $(ps ax | grep -q '[t]ini'); then
+        echo "WARNING: 'tini' process is missing."
+    fi
+
+    echo $ERRORS
+    [[ ERRORS -eq 0 ]] || exit 1
+
+    echo "Starting Breeze daemon..."
+    /opt/breeze-agent/breeze-daemon
+
+---
 {{- if and (eq .Values.platform "eks") (not .Values.eksMetadataAccess) }}
 apiVersion: v1
 kind: ConfigMap
